### ISSUE TITLE
Version 1.4.5 throws error when submitting list

### ISSUE THREAD

**Issue by Zamrod** [Moerill/fvtt-find-the-culprit#35]
Foundry v10.286
dnd5e 2.0.3
FTC 1.4.5

Whenever you try to use FTC now it gives the following error in the console and doesn't refresh the page. Manually refreshing the page just brings back the same prompt asking if the error is occurring still or not. This worked fine until 1.4.5

```
Uncaught (in promise) TypeError: game.settings.set(...) is not a function
[Detected 1 package: find-the-culprit]
    at reactivateModules (find-the-culprit.js:361:3)
    at Object.callback (find-the-culprit.js:239:25)
    at Dialog.submit (foundry.js:55745:35)
    at Dialog._onClickButton (foundry.js:55674:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by MrPotatoZed** [comment]
Seeing the same behavior/error. v10. 286, 5e 2.0.3, FTC 1.4.5.

**Comment by mouse0270** [comment]
Its a semicolon issue. I've made a pull request to fix it. #34
